### ISSUE TITLE
Socket Hang Up

### ISSUE THREAD

**Issue by rbaid1221** [cometd/cometd-javascript#1] opened 2018-10-04 22:07 UTC
At first this module was working great! But after sending cometd, connection requests, it is now returning as successful: false, with no advice, and says the transport has been closed.

Any idea what I should have a look at?

Connect
{ id: '5',
  successful: false,
  channel: '/meta/connect',
  failure: 
   { reason: 'socket hang up',
     exception: undefined,
     httpCode: 0,
     connectionType: 'long-polling',
     transport: 
      { status: 0,
        statusText: 'socket hang up',
        readyState: 4,
        responseText: '',
        open: [Function],
        setRequestHeader: [Function],
        send: [Function],
        abort: [Function],
        _config: [Function],
        context: undefined,
        withCredentials: true,
        onload: [Function],
        onerror: [Function] },
     message: 
      { id: '5',
        channel: '/meta/connect',
        connectionType: 'long-polling',
        clientId: '----deleted' } } }

**Comment by sbordet** [comment] 2018-10-05 06:25
Duplicate of cometd/cometd-nodejs-client#12.

**Closed as completed by sbordet** 2018-10-05 06:25 UTC
