### ISSUE TITLE
Scheduler not working randomly when cometd object is reconfigured at runtime.

### ISSUE THREAD

**Issue by shrihari-prakash** [cometd/cometd-javascript#2] opened 2023-03-08 06:29 UTC
CometD version(s): 3.1.12

I had been debugging an application which uses cometd and found that at times, when cometd is reconfigured with different URL at runtime, setTimeouts in Scheduler object would randomly stop working. This results in `/connect` requests not being initiated after handshake. I checked the cometd client-side code and it looks like if the Scheduler object is re-instantiated every time cometd is configured, this issue is fixed (to me, it looks like if we are using the old scheduler every time cometd is configured, it might be using a garbage collected worker or something like that?). So, I suggest adding the following line before the `setTimeout` is overridden (after line `1478` of https://github.com/cometd/cometd-javascript/blob/3.1.x/cometd.js, after `if (window.Worker && window.Blob && window.URL && _config.useWorkerScheduler) {`):

`_scheduler = new Scheduler();`

Also initializing Scheduler object to null at first might be a good idea for performance if this line is added.

Can you confirm if this can be implemented in the library? If you require, I can raise a PR.

**Comment by sbordet** [comment] 2023-03-09 16:42
Duplicate of cometd/cometd#1327.

**Closed as completed by sbordet** 2023-03-09 16:42 UTC
